// index.jsx

import { Container } from 'components/container'
import Head from 'next/head'
import { Hero } from 'components/hero/'
import { Icon } from 'components/awesomeicon'

export default function Home() {
  return (
    <>
      <Head>
        <title>Index.page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Hero title="index" subtitle="最初に実行される特別な名前" imageOn />
        <Icon />
      </Container>
    </>
  )
}
