// index.jsx

import Head from 'next/head'
import { Hero } from 'components/hero'

export default function Home() {
  return (
    <>
      <Head>
        <title>Index.page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero title="yasuhiro" subtitle="いつでも最高の学習を！" imageOn />
    </>
  )
}
